name: Deploy React App to Ubuntu Server

on:
  push:
    branches: ["react-web"]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

      - name: Deploy build to server
        run: |
          sudo rm -rf /var/www/ippeba/*
          sudo mkdir -p /var/www/ippeba
          sudo cp -r build/* /var/www/ippeba/

#jekyll-gh-pages.yml
# name: Deploy React App to GitHub Pages

# on:
#   push:
#     branches: ["react-web"] # default branch

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# concurrency:
#   group: "pages"
#   cancel-in-progress: false

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20" # or your preferred version

#       - name: Install dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: "./build" # This is the default build folder for Create React App

#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
